// Generated by CoffeeScript 1.9.2
var setup;

setup = {
  view: 'kitchensink.svg',
  font: {
    families: {
      'PTSans': 'PT Sans'
    },
    weights: {
      'Regular': 400,
      'Bold': 600
    },
    styles: {
      'Italic': 'italic'
    }
  }
};

new Prototype(setup);
